# application.yml - Updated with Parallel Processing Support

spring:
  application:
    name: shopee-etl-production

  # Production Database Configuration
  datasource:
    url: jdbc:postgresql://103.97.125.92:5432/guno_db?useSSL=false
    username: guno_user
    password: UYUgjL80moKrc6WTDLbg
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    banner-mode: "console"

# ETL Configuration for Production
etl:
  # 🆕 PARALLEL PROCESSING CONFIGURATION
  parallel:
    enabled: true                    # Enable/disable parallel processing
    timeout-minutes: 15              # Global timeout for all platforms
    thread-pool-size: 5              # Thread pool size for parallel execution
    facebook-special-timeout: 10     # Special timeout for Facebook (minutes)
    enable-detailed-logging: true    # Enable detailed parallel processing logs

  # Platform Settings
  platforms:
    shopee:
      enabled: true
      name: SHOPEE
    tiktok:
      enabled: true
      name: TIKTOK
    facebook:
      enabled: true
      name: FACEBOOK

  # 🆕 UPDATED API CONFIGURATION - INCREASED PAGE SIZES
  api:
    shopee:
      base-url: https://n8n.guno.club/webhook/ddaece67-7b38-4c3d-a31d-d50c9cfd89c8/hub-data/orders/shopee
      auth-header: x-webhook-api-key
      api-key: iuKqTys2XUNJOFLhByaH3woWsrLDC5yajHu7dvSe63U34qN57Zi9bNxeMj2FQc9qcn8sgQr
      timeout: 300
      page-size: 1500                # 🆕 INCREASED from 1000 to 1500
      max-retries: 3

    tiktok:
      base-url: https://n8n.guno.club/webhook/ddaece67-7b38-4c3d-a31d-d50c9cfd89c8/hub-data/orders/tiktok
      auth-header: x-webhook-api-key
      api-key: iuKqTys2XUNJOFLhByaH3woWsrLDC5yajHu7dvSe63U34qN57Zi9bNxeMj2FQc9qcn8sgQr
      timeout: 300
      page-size: 1500                # 🆕 INCREASED from 1000 to 1500
      max-retries: 3

    facebook:
      base-url: https://hub-bak.guno.store/api/v1/pos/pos-pancake-fm/order/search
      auth-header: x-webhook-api-key
      api-key: iuKqTys2XUNJOFLhByaH3woWsrLDC5yajHu7dvSe63U34qN57Zi9bNxeMj2FQc9qcn8sgQr
      timeout: 600                   # 🆕 INCREASED from 300 to 600 (10 minutes)
      page-size: 1000                # Keep at 1000 for Facebook due to API constraints
      max-retries: 5                 # 🆕 INCREASED from 3 to 5
      retry-delay-seconds: 2         # 🆕 NEW: Delay between retries
      enable-exponential-backoff: true # 🆕 NEW: Enable exponential backoff for retries

  # Scheduler Settings
  scheduler:
    enabled: true
    fixed-rate: 30000              # 30 seconds
    initial-delay: 5000            # 5 second startup delay
    max-consecutive-failures: 5
    use-parallel-processing: true   # 🆕 NEW: Use parallel processing in scheduler

  # Database Settings
  database:
    batch-size: 50

# Production Logging - Enhanced for Parallel Processing
logging:
  level:
    root: INFO
    com.guno.etl: INFO
    com.guno.etl.service: INFO
    com.guno.etl.service.ParallelApiService: DEBUG  # 🆕 NEW: Detailed logging for parallel service
    com.guno.etl.scheduler: INFO
    org.springframework.web.reactive: WARN
    org.springframework.transaction: WARN
    org.hibernate.SQL: WARN
    org.springframework.boot: INFO

  file:
    name: logs/shopee-etl-production.log
    max-size: 100MB
    max-history: 30

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

# Production Server Settings
server:
  port: 8080
  servlet:
    context-path: /etl
  compression:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 10

# 🆕 NEW: Performance Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true